{% set temp_name = temp_name|default('') %}


{# ~~~~~~~~~~~~~~~~~~~~~~~~~~~ status_code ~~~~~~~~~~~~~~~~~~~~~~~~~~~ #}
status_code: {{ status_code }}
{# ~~~~~~~~~~~~~~~~~~~~~~~~~~~ status_code ~~~~~~~~~~~~~~~~~~~~~~~~~~~ #}


{# ~~~~~~~~~~~~~~~~~~~~~~~~~~~ content ~~~~~~~~~~~~~~~~~~~~~~~~~~~ #}
content:
  {% block content %}
  {% endblock %}
{# ~~~~~~~~~~~~~~~~~~~~~~~~~~~ content ~~~~~~~~~~~~~~~~~~~~~~~~~~~ #}